name: Blink Investments
favicon: null
layout_spectrum: 0.27058
typography_spectrum: 0.39259
title: Blink Investments - Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c9d5e3'
    - '#b1bd2b'
    - '#2a370c'
    - '#83756a'
  brandStrength: 0.06091179698705673
  lightness: 0.7912083608098328
  saturation: 0.5913835223764181
  rhythmicContrast: 0.3178323497995734
purpose: []
