name: Blink Investments
favicon: null
layout_spectrum: 0.21276896633207798
typography_spectrum: 0.01867504487745464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.06091179698705673
  lightness: 0.7912083608098328
  saturation: 0.5913835223764181
  rhythmicContrast: 0.3178323497995734
purpose: []
